# Generated by Django 5.0.6 on 2024-06-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_additive', models.BooleanField(default=False, verbose_name='Is it additive?')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('product_hierarchy_a', models.CharField(blank=True, max_length=100, null=True)),
                ('product_hierarchy_b', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='CreateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive', models.CharField(max_length=100, verbose_name='Is it Additive?')),
                ('mg_code', models.CharField(max_length=200)),
                ('ph_code', models.CharField(max_length=200)),
                ('additive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additive_type', to='cal.materialgroup', verbose_name='What Additive Type or Industry Served?')),
                ('color_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_type', to='cal.materialgroup', verbose_name='Color')),
                ('ink_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ink_type', to='cal.materialgroup', verbose_name='Ink Type')),
                ('liquied_narrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquied_narrow', to='cal.materialgroup', verbose_name='Is it for Liquid Packaging or a Narrow Web?')),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='press', to='cal.materialgroup', verbose_name='Press')),
                ('resin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resin', to='cal.materialgroup', verbose_name='What Resin is mostly Used')),
                ('special_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_attribute', to='cal.materialgroup', verbose_name='Any Special Attributes (Fade Resist, Fluorescents, Low Copper Requirements):')),
                ('special_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_requirement', to='cal.materialgroup', verbose_name='What Type of Special Requirements:')),
                ('swu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swu', to='cal.materialgroup', verbose_name='Is it Solven, Water, UV?')),
            ],
        ),
    ]
