# Generated by Django 5.0.6 on 2024-06-15 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcode',
            name='additive',
            field=models.CharField(max_length=100, verbose_name='Is it Additive?:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='additive_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additive_type', to='cal.materialgroup', verbose_name='What Additive Type or Industry Served?:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='color_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_type', to='cal.materialgroup', verbose_name='Color:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='ink_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ink_type', to='cal.materialgroup', verbose_name='Ink Type:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='liquied_narrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquied_narrow', to='cal.materialgroup', verbose_name='Is it for Liquid Packaging or a Narrow Web?:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='mg_code',
            field=models.CharField(max_length=200, verbose_name='Material Group Code:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='ph_code',
            field=models.CharField(max_length=200, verbose_name='Product Hierarchy Code:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='press',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='press', to='cal.materialgroup', verbose_name='Press:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='resin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resin', to='cal.materialgroup', verbose_name='What Resin is mostly Used?:'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='special_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_attribute', to='cal.materialgroup', verbose_name='Any Special Attributes (Fade Resist, Fluorescents, Low Copper):'),
        ),
        migrations.AlterField(
            model_name='createcode',
            name='swu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swu', to='cal.materialgroup', verbose_name='Is it Solven, Water, UV?:'),
        ),
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=100)),
                ('color_type_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.materialgroup')),
            ],
        ),
    ]
