# Generated by Django 5.0.6 on 2024-06-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_createcode_additive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcode',
            name='color_code_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_code_choice', to='cal.colorcode', verbose_name='Select Color Code:'),
        ),
    ]
