# Generated by Django 5.0.6 on 2024-06-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_colorcode_material_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorcode',
            name='color_code',
            field=models.CharField(max_length=100, verbose_name='Color Code'),
        ),
        migrations.AlterField(
            model_name='colorcode',
            name='color_type_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.materialgroup', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='colorcode',
            name='material_group',
            field=models.CharField(max_length=100, verbose_name='Color Code Value'),
        ),
    ]
